"""added indexes to the notes

Revision ID: 35b4482bfd7b
Revises: e5e7cfd360de
Create Date: 2025-12-14 17:13:00.874768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b4482bfd7b'
down_revision: Union[str, Sequence[str], None] = 'e5e7cfd360de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notes_user_active', 'notes', ['user_id', 'is_deleted', 'updated_at'], unique=False)
    op.create_index('idx_notes_user_created', 'notes', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notes_user_title', 'notes', ['user_id', 'title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notes_user_title', table_name='notes')
    op.drop_index('idx_notes_user_created', table_name='notes')
    op.drop_index('idx_notes_user_active', table_name='notes')
    # ### end Alembic commands ###
