"""added is_deleted to notes table

Revision ID: e5e7cfd360de
Revises: 8c99ec23db95
Create Date: 2025-12-14 15:04:19.462021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e7cfd360de'
down_revision: Union[str, Sequence[str], None] = '8c99ec23db95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_deleted')
    # ### end Alembic commands ###
